/*
 * smk_autogen.c - autogen.py output (cycle-accurate recomp_tick calls).
 * Entry flags come from a real-ROM profile; main.c selects the oracle-gated
 * default subset. Other generated bodies remain opt-in for focused work.
 * Regenerate: py tools/recomp/gen_set.py <rom> <prof> <this>
 */
#include "smk/functions.h"
#include "smk/recomp_ops.h"
#include <snesrecomp/snesrecomp.h>
#include <snesrecomp/func_table.h>
#include <stdint.h>

/* Link anchor: forces this static-lib TU (and its registrations) to link. */
void smk_autogen_link_anchor(void) {}


/* Auto-generated by tools/recomp/autogen.py from $80:F90A
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80F90A, 0x80F90A) {
    goto L_F90A;
  L_F90A:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5A + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F90A LDA */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)(_x << 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F90C ASL */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_F927;  /* $F90D BCS */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5E + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F90F LDA */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_F924;  /* $F911 BNE */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x5C + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F913 LDA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_F91C;  /* $F915 BEQ */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F917 DEC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x5C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F918 STA */
    recomp_tick(12);
    goto L_F927;   /* $F91A BRA */
  L_F91C:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F91C LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xBFFF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F91E AND */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F921 STA */
    recomp_tick(24);
    return;            /* $F923 RTS */
  L_F924:;
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F924 DEC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x5E + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F925 STA */
  L_F927:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F927 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x4000); _a = (uint16_t)(_a | _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F929 ORA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $F92C STA */
    recomp_tick(12);
    g_cpu.flag_C = 1;                              /* $F92E SEC */
    recomp_tick(24);
    return;            /* $F92F RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:A01F
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80A01F, 0x80A01F) {
    goto L_A01F;
  L_A01F:;
    recomp_tick(28);
    op_phx16();                                    /* $A01F PHX */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A020 LDY */
    recomp_tick(40);
    func_table_call_jsr(0x80A027);  /* $A022 JSR */
    recomp_tick(34);
    op_plx16();                                    /* $A025 PLX */
    recomp_tick(24);
    return;            /* $A026 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:A027
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80A027, 0x80A027) {
    goto L_A027;
  L_A027:;
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.Y); uint16_t _v = (uint16_t)(0x0000); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $A027 CPY */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_A05B;  /* $A02A BEQ */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x010E + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A02C LDX */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_A05B;  /* $A02F BEQ */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC0 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A031 LDA */
    recomp_tick(28);
    op_phx16();                                    /* $A033 PHX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x010C + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A034 LDX */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_A05A;  /* $A037 BEQ */
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC0 + g_cpu.X))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $A039 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_A05A;  /* $A03B BEQ */
    recomp_tick(12);
    if (!g_cpu.flag_C) goto L_A05A;  /* $A03D BCC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $A03F LDA */
    recomp_tick(18);
    g_cpu.flag_Z = (uint8_t)(((uint16_t)(g_cpu.C) & (uint16_t)0x0020) == 0); /* $A041 BIT */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_A05A;  /* $A044 BNE */
    recomp_tick(12);
    op_txa();                                      /* $A046 TXA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x010E + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $A047 STA */
    recomp_tick(12);
    op_tya();                                      /* $A04A TYA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $A04B STA */
    recomp_tick(34);
    op_plx16();                                    /* $A04D PLX */
    recomp_tick(12);
    op_txa();                                      /* $A04E TXA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x010C + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $A04F STA */
    recomp_tick(12);
    op_tya();                                      /* $A052 TYA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $A053 DEC */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $A054 DEC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xE6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $A055 STA */
    recomp_tick(12);
    op_tay();                                      /* $A057 TAY */
    recomp_tick(12);
    goto L_A027;   /* $A058 BRA */
  L_A05A:;
    recomp_tick(34);
    op_plx16();                                    /* $A05A PLX */
  L_A05B:;
    recomp_tick(24);
    return;            /* $A05B RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:8902
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_818902, 0x818902) {
    goto L_8902;
  L_8902:;
    recomp_tick(18);
    op_sep(0x30);                                  /* $8902 SEP */
    recomp_tick(26);
    { uint8_t _m = (uint8_t)(bus_read8(g_cpu.DB, 0x1F06)); uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); g_cpu.flag_Z = (uint8_t)((_a & _m) == 0); g_cpu.flag_N = (uint8_t)((_m >> 7) & 1); g_cpu.flag_V = (uint8_t)((_m >> 6) & 1); } /* $8904 BIT */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_8918;  /* $8907 BPL */
    recomp_tick(12);
    { uint8_t _v = (uint8_t)(0x08); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8909 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2100, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $890B STA */
    recomp_tick(12);
    { uint8_t _v = (uint8_t)(0x10); g_cpu.X = (uint16_t)((_v) & 0xFF); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $890E LDX */
  L_8910:;
    recomp_tick(12);
    { uint8_t _t = (uint8_t)(((uint8_t)(g_cpu.X & 0xFF)) - 1); g_cpu.X = (uint16_t)((_t) & 0xFF); g_cpu.flag_N = (uint8_t)(((uint8_t)(_t) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_t) == 0); } /* $8910 DEX */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8910;  /* $8911 BNE */
    recomp_tick(12);
    { uint8_t _v = (uint8_t)(0x0F); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8913 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2100, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8915 STA */
  L_8918:;
    recomp_tick(18);
    op_rep(0x30);                                  /* $8918 REP */
    recomp_tick(24);
    return;            /* $891A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:B9A8
 * entry M=1 X=0 (P=$20). Validate with the diff harness. */
RECOMP_PATCH(smk_81B9A8, 0x81B9A8) {
    goto L_B9A8;
  L_B9A8:;
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $B9A8 LDA */
    recomp_tick(12);
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AB LSR */
    recomp_tick(12);
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AC LSR */
    recomp_tick(12);
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AD LSR */
    recomp_tick(12);
    { uint8_t _x = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _c = (uint8_t)(_x & 1); uint8_t _r = (uint8_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_r) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_r) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_r) == 0); } /* $B9AE LSR */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x80); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9AF ORA */
    recomp_tick(20);
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x2C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9B1 STA */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x10); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9B3 ORA */
    recomp_tick(20);
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x6C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9B5 STA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9B7 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9B8 INX */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $B9B9 LDA */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x0F); _a = (uint8_t)(_a & _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9BC AND */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x80); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9BE ORA */
    recomp_tick(20);
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x2C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9C0 STA */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x10); _a = (uint8_t)(_a | _v); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_a) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_a) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_a) == 0); } /* $B9C2 ORA */
    recomp_tick(20);
    bus_write8(0x00, (uint16_t)(g_cpu.DP + 0x6C + g_cpu.X), (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $B9C4 STA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C6 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C7 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C8 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B9C9 INX */
    recomp_tick(24);
    return;            /* $B9CA RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:8BBF
 * entry M=1 X=1 (P=$30). Validate with the diff harness. */
RECOMP_PATCH(smk_808BBF, 0x808BBF) {
    goto L_8BBF;
  L_8BBF:;
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016A + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BBF LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2131, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BC2 STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016C + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BC5 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BC8 STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x016E + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BCB LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BCE STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0170 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BD1 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2132, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BD4 STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x0108 + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BD7 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2125, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BDA STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x014E + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BDD LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x212E, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BE0 STA */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, (uint16_t)(0x017A + g_cpu.X))); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $8BE3 LDA */
    recomp_tick(24);
    bus_write8(g_cpu.DB, 0x2130, (uint8_t)((uint8_t)(g_cpu.C & 0xFF))); /* $8BE6 STA */
    recomp_tick(24);
    return;            /* $8BE9 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:86A0
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8086A0, 0x8086A0) {
    goto L_86A0;
  L_86A0:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xA4 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86A0 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0002); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $86A2 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_86AB;  /* $86A5 BEQ */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xAC + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86A7 LDA */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_86CB;  /* $86A9 BPL */
  L_86AB:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0016 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86AB LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00), (uint16_t)(g_cpu.C)); /* $86AE STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0018 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86B0 LDA */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B3 ROL */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B5 ROL */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B6 ROL */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86B8 ROL */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x88 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $86B9 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x001A + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86BB LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00), (uint16_t)(g_cpu.C)); /* $86BE STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x001C + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $86C0 LDA */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C3 ROL */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C5 ROL */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C6 ROL */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)((_x << 1) | (g_cpu.flag_C ? 1 : 0)); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $86C8 ROL */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x8C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $86C9 STA */
  L_86CB:;
    recomp_tick(24);
    return;            /* $86CB RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:BBCC
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80BBCC, 0x80BBCC) {
    goto L_BBCC;
  L_BBCC:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB8))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBCC LDX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x1E96 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBCE LDA */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_BBFE;  /* $BBD1 BPL */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x1EB0 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBD3 LDA */
    recomp_tick(12);
    if (g_cpu.flag_N) goto L_BBE2;  /* $BBD6 BMI */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x8000); _a = (uint16_t)(_a | _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BBD8 ORA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x1EB0 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $BBDB STA */
    recomp_tick(54);
    func_table_call(0x81AF50);  /* $BBDE JSL */
  L_BBE2:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0020); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBE2 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x1EF8 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $BBE5 STA */
    recomp_tick(54);
    func_table_call(0x81BB4A);  /* $BBE8 JSL */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0xD3A1); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBEC LDX */
    recomp_tick(54);
    func_table_call(0x81CC26);  /* $BBEF JSL */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0xD3B0); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BBF3 LDX */
    recomp_tick(54);
    func_table_call(0x81CC26);  /* $BBF6 JSL */
    recomp_tick(54);
    func_table_call(0x81AFB4);  /* $BBFA JSL */
  L_BBFE:;
    recomp_tick(24);
    return;            /* $BBFE RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:BA50
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80BA50, 0x80BA50) {
    goto L_BA50;
  L_BA50:;
    recomp_tick(18);
    { g_cpu.S--; bus_wram_write16(g_cpu.S, 0x8085); g_cpu.S--; } /* $BA50 PEA */
    recomp_tick(26);
    op_plb();                                      /* $BA53 PLB */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB8))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BA54 LDX */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC8 + g_cpu.X))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BA56 LDY */
    recomp_tick(12);
    if (g_cpu.flag_N) goto L_BA5E;  /* $BA58 BMI */
    recomp_tick(54);
    func_table_call(0x85DFB4);  /* $BA5A JSL */
  L_BA5E:;
    recomp_tick(26);
    op_plb();                                      /* $BA5E PLB */
    recomp_tick(24);
    return;            /* $BA5F RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:8D83
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_808D83, 0x808D83) {
    goto L_8D83;
  L_8D83:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2C))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D83 LDA */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8DD0;  /* $8D85 BNE */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x012E)); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D87 LDX */
    recomp_tick(34);
    { uint16_t _a = (uint16_t)(g_cpu.X); uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0144)); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8D8A CPX */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_8DD0;  /* $8D8D BCS */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x4A))); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D8F LDY */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DD1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D91 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA0 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8D94 STA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $8D97 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0100); smk_op_adc16(_v); } /* $8D98 ADC */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA6 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8D9B STA */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x407F); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8D9E LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA4 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DA1 STA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EAA + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DA4 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0130 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DA7 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.X); uint16_t _v = (uint16_t)(0x0008); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8DAA CPX */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_8DB5;  /* $8DAD BCS */
    recomp_tick(12);
    op_tax();                                      /* $8DAF TAX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DE1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DB0 LDA */
    recomp_tick(12);
    goto L_8DB9;   /* $8DB3 BRA */
  L_8DB5:;
    recomp_tick(12);
    op_tax();                                      /* $8DB5 TAX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8DF1 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8DB6 LDA */
  L_8DB9:;
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA2 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DB9 STA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $8DBC CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0200); smk_op_adc16(_v); } /* $8DBD ADC */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA8 + g_cpu.Y), (uint16_t)(g_cpu.C)); /* $8DC0 STA */
    recomp_tick(12);
    op_tya();                                      /* $8DC3 TYA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $8DC4 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x000C); smk_op_adc16(_v); } /* $8DC5 ADC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x4A), (uint16_t)(g_cpu.C)); /* $8DC8 STA */
    recomp_tick(56);
    { uint8_t _bk = (uint8_t)(g_cpu.DB); uint16_t _ad = (uint16_t)(0x012E); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8DCA INC */
    recomp_tick(56);
    { uint8_t _bk = (uint8_t)(g_cpu.DB); uint16_t _ad = (uint16_t)(0x012E); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8DCD INC */
  L_8DD0:;
    recomp_tick(24);
    return;            /* $8DD0 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:B7EB
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_80B7EB, 0x80B7EB) {
    goto L_B7EB;
  L_B7EB:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B7EB LDA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_B80F;  /* $B7ED BEQ */
    recomp_tick(12);
    if (g_cpu.flag_N) goto L_B7F7;  /* $B7EF BMI */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B7F1 DEC */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_B804;  /* $B7F2 BEQ */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B7F4 STA */
    recomp_tick(24);
    return;            /* $B7F6 RTS */
  L_B7F7:;
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B7F7 INC */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_B7FD;  /* $B7F8 BEQ */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B7FA STA */
    recomp_tick(24);
    return;            /* $B7FC RTS */
  L_B7FD:;
    recomp_tick(40);
    func_table_call_jsr(0x80B847);  /* $B7FD JSR */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B800 STA */
    recomp_tick(12);
    goto L_B826;   /* $B802 BRA */
  L_B804:;
    recomp_tick(40);
    func_table_call_jsr(0x80B847);  /* $B804 JSR */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFFFF); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $B807 EOR */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B80A INC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B80B STA */
    recomp_tick(12);
    goto L_B815;   /* $B80D BRA */
  L_B80F:;
    recomp_tick(40);
    func_table_call_jsr(0x80B847);  /* $B80F JSR */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xC6 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B812 STA */
    recomp_tick(24);
    return;            /* $B814 RTS */
  L_B815:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B815 LDA */
    recomp_tick(12);
    op_tay();                                      /* $B817 TAY */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0xB837 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B818 LDA */
    recomp_tick(28);
    op_phx16();                                    /* $B81B PHX */
    recomp_tick(12);
    op_tax();                                      /* $B81C TAX */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x35A9); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B81D LDA */
    recomp_tick(40);
    bus_write16(0x7E, (uint16_t)(0x3A80 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B820 STA */
    recomp_tick(34);
    op_plx16();                                    /* $B824 PLX */
    recomp_tick(24);
    return;            /* $B825 RTS */
  L_B826:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B826 LDA */
    recomp_tick(12);
    op_tay();                                      /* $B828 TAY */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0xB837 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B829 LDA */
    recomp_tick(28);
    op_phx16();                                    /* $B82C PHX */
    recomp_tick(12);
    op_tax();                                      /* $B82D TAX */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x2525); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $B82E LDA */
    recomp_tick(40);
    bus_write16(0x7E, (uint16_t)(0x3A80 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $B831 STA */
    recomp_tick(34);
    op_plx16();                                    /* $B835 PLX */
    recomp_tick(24);
    return;            /* $B836 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:9EB2
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_809EB2, 0x809EB2) {
    goto L_9EB2;
  L_9EB2:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0E68)); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB2 LDA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_9EC7;  /* $9EB5 BEQ */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x32))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EB7 LDA */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_9EC7;  /* $9EB9 BNE */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EBB LDX */
    recomp_tick(40);
    func_table_call_jsr(0x809FAC);  /* $9EBE JSR */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0002); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9EC1 LDX */
    recomp_tick(40);
    func_table_call_jsr(0x809FAC);  /* $9EC4 JSR */
  L_9EC7:;
    recomp_tick(24);
    return;            /* $9EC7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:84D1
 * entry M=1 X=1 (P=$30). Validate with the diff harness. */
RECOMP_PATCH(smk_8584D1, 0x8584D1) {
    goto L_84D1;
  L_84D1:;
    recomp_tick(18);
    op_rep(0x20);                                  /* $84D1 REP */
    recomp_tick(50);
    op_inc_dp16(0x64);                             /* $84D3 INC */
    recomp_tick(18);
    op_sep(0x20);                                  /* $84D5 SEP */
    recomp_tick(24);
    return;            /* $84D7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8EE9
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858EE9, 0x858EE9) {
    goto L_8EE9;
  L_8EE9:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x75))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EE9 LDA */
    recomp_tick(12);
    op_tax();                                      /* $8EEB TAX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FE9 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EEC LDA */
    recomp_tick(12);
    op_tax();                                      /* $8EEF TAX */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EF0 LDA */
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8EF2 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8EFA;  /* $8EF4 BNE */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8EF6 INC */
    recomp_tick(18);
    func_table_call_jsr(0x858EFB); return;  /* $8EF7 JMP (tail) */
  L_8EFA:;
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) - 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8EFA DEC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8EFB STA */
    recomp_tick(50);
    op_inc_dp16(0x75);                             /* $8EFD INC */
    recomp_tick(50);
    op_inc_dp16(0x75);                             /* $8EFF INC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x75))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F01 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0010); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8F03 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8F0A;  /* $8F06 BNE */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x75), (uint16_t)(0)); /* $8F08 STZ */
  L_8F0A:;
    recomp_tick(24);
    return;            /* $8F0A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:B945
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_85B945, 0x85B945) {
    goto L_B945;
  L_B945:;
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B945 INY */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B946 INY */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B947 INY */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.Y) + 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $B948 INY */
    recomp_tick(24);
    return;            /* $B949 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8FB8
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858FB8, 0x858FB8) {
    goto L_8FB8;
  L_8FB8:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x8FF9 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FB8 LDA */
    recomp_tick(12);
    op_tay();                                      /* $8FBB TAY */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x22 + g_cpu.X), (uint16_t)(0)); /* $8FBC STZ */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FBE LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x18 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC1 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC3 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x1C + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FC6 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FC8 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x2A + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FCB STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FCD LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x92 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD0 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8FD2 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x44 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8FD5 STA */
    recomp_tick(24);
    return;            /* $8FD7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:8B7A
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_858B7A, 0x858B7A) {
    goto L_8B7A;
  L_8B7A:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x0048)); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8B7A LDA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8B80;  /* $8B7D BEQ */
    recomp_tick(24);
    return;            /* $8B7F RTS */
  L_8B80:;
    recomp_tick(40);
    func_table_call_jsr(0x858EE9);  /* $8B80 JSR */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x1000); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8B83 LDX */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x40 + g_cpu.X)); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8B86 INC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x40 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8B88 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x00D2); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8B8A CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8B8D BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x01F2); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8B8F CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8B92 BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0452); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8B94 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8B97 BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x046A); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8B99 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8B9C BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x053A); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8B9E CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8BA1 BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0592); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8BA3 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8BAB;  /* $8BA6 BEQ */
    recomp_tick(18);
    func_table_call_jsr(0x858BAD); return;  /* $8BA8 JMP (tail) */
  L_8BAB:;
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x42 + g_cpu.X)); uint16_t _t = (uint16_t)(bus_read16(_bk, _ad) + 1); bus_write16(_bk, _ad, _t); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8BAB INC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x42 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8BAD LDA */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)(_x << 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $8BAF ASL */
    recomp_tick(12);
    op_tax();                                      /* $8BB0 TAX */
    recomp_tick(18);
    { uint16_t _t = bus_read16(0x85, (uint16_t)(0x8BB4 + g_cpu.X)); func_table_call_jsr(((uint32_t)0x85 << 16) | _t); } return;  /* $8BB1 JMP (tail) */
}

/* Auto-generated by tools/recomp/autogen.py from $81:81C4
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8181C4, 0x8181C4) {
    goto L_81C4;
  L_81C4:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x81A8); g_cpu.Y = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81C4 LDY */
    recomp_tick(12);
    goto L_81CC;   /* $81C7 BRA */
  L_81CC:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0000 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81CC LDX */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xB8), (uint16_t)(g_cpu.X)); /* $81CF STX */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x1EF8 + g_cpu.X), (uint16_t)(0)); /* $81D1 STZ */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xC8 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D4 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x0FE0, (uint16_t)(g_cpu.C)); /* $81D6 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0002 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81D9 LDX */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCE), (uint16_t)(g_cpu.X)); /* $81DC STX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0004 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81DE LDX */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xCC), (uint16_t)(g_cpu.X)); /* $81E1 STX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0006 + g_cpu.Y))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E3 LDX */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xBA), (uint16_t)(g_cpu.X)); /* $81E6 STX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x0008 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81E8 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x0FE2, (uint16_t)(g_cpu.C)); /* $81EB STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000A + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81EE LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x0FE4, (uint16_t)(g_cpu.C)); /* $81F1 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x000C + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $81F4 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x0FDC, (uint16_t)(g_cpu.C)); /* $81F7 STA */
    recomp_tick(24);
    return;            /* $81FA RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:92F9
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8592F9, 0x8592F9) {
    goto L_92F9;
  L_92F9:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x48))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $92F9 LDA */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_9331;  /* $92FB BNE */
    recomp_tick(18);
    op_sep(0x20);                                  /* $92FD SEP */
    recomp_tick(26);
    { uint8_t _v = (uint8_t)(bus_read8(g_cpu.DB, 0x0161)); g_cpu.C = (uint16_t)((g_cpu.C & 0xFF00) | ((_v) & 0xFF)); g_cpu.flag_N = (uint8_t)(((uint8_t)(_v) >> 7) & 1); g_cpu.flag_Z = (uint8_t)((uint8_t)(_v) == 0); } /* $92FF LDA */
    recomp_tick(12);
    { uint8_t _a = (uint8_t)((uint8_t)(g_cpu.C & 0xFF)); uint8_t _v = (uint8_t)(0x0F); uint8_t _t = (uint8_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 7) & 1); } /* $9302 CMP */
    recomp_tick(18);
    op_rep(0x20);                                  /* $9304 REP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_9331;  /* $9306 BNE */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x28))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9308 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6A), (uint16_t)(g_cpu.C)); /* $930A STA */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2A))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $930C LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6C), (uint16_t)(g_cpu.C)); /* $930E STA */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x36))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9310 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0004); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9312 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_931F;  /* $9315 BEQ */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0006); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9317 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_9320;  /* $931A BEQ */
  L_931C:;
    recomp_tick(40);
    func_table_call_jsr(0x859336);  /* $931C JSR */
  L_931F:;
    recomp_tick(24);
    return;            /* $931F RTS */
  L_9320:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2C))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9320 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0004); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9322 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_931C;  /* $9325 BNE */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x2E))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $9327 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0002); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $9329 CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_931F;  /* $932C BEQ */
    recomp_tick(18);
    func_table_call_jsr(0x85931C); return;  /* $932E JMP (tail) */
  L_9331:;
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6A), (uint16_t)(0)); /* $9331 STZ */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x6C), (uint16_t)(0)); /* $9333 STZ */
    recomp_tick(24);
    return;            /* $9335 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $80:8EED
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_808EED, 0x808EED) {
    goto L_8EED;
  L_8EEA:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x4A))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EEA LDX */
    recomp_tick(24);
    return;            /* $8EEC RTS */
  L_8EED:;
    recomp_tick(50);
    op_inc_dp16(0x1E);                             /* $8EED INC */
    recomp_tick(18);
    op_xba();                                      /* $8EEF XBA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x1000); _a = (uint16_t)(_a | _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $8EF0 ORA */
    recomp_tick(12);
    op_tax();                                      /* $8EF3 TAX */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EF4 LDA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8EEA;  /* $8EF6 BEQ */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x30 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8EF8 LDA */
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xBA + g_cpu.X))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8EFA CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8EEA;  /* $8EFC BEQ */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0xBA + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8EFE STA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x7FFF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $8F00 AND */
    recomp_tick(12);
    op_tay();                                      /* $8F03 TAY */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x016E); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8F04 CMP */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_8EEA;  /* $8F07 BCS */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x016A); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8F09 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_C) goto L_8F1C;  /* $8F0C BCC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x08), (uint16_t)(0)); /* $8F0E STZ */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_8F17;  /* $8F10 BEQ */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0400); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F12 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x08), (uint16_t)(g_cpu.C)); /* $8F15 STA */
  L_8F17:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB6 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F17 LDA */
    recomp_tick(18);
    func_table_call_jsr(0x808FAE); return;  /* $8F19 JMP (tail) */
  L_8F1C:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0xB6 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F1C LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10), (uint16_t)(g_cpu.C)); /* $8F1E STA */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F20 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0002); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $8F22 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8F32;  /* $8F25 BNE */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x9292 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F27 LDA */
    recomp_tick(12);
    if (g_cpu.flag_N) goto L_8F2F;  /* $8F2A BMI */
    recomp_tick(18);
    func_table_call_jsr(0x808FE5); return;  /* $8F2C JMP (tail) */
  L_8F2F:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F2F LDA */
  L_8F32:;
    recomp_tick(12);
    op_tax();                                      /* $8F32 TAX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x9080 + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F33 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x16), (uint16_t)(g_cpu.C)); /* $8F36 STA */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x9090 + g_cpu.Y))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F38 LDA */
    recomp_tick(28);
    op_pha16();                                    /* $8F3B PHA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x00FF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $8F3C AND */
    recomp_tick(12);
    op_tax();                                      /* $8F3F TAX */
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, (uint16_t)(0x91FA + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F40 LDA */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x12), (uint16_t)(g_cpu.C)); /* $8F43 STA */
    recomp_tick(34);
    op_pla16();                                    /* $8F45 PLA */
    recomp_tick(18);
    op_xba();                                      /* $8F46 XBA */
    recomp_tick(28);
    op_pha16();                                    /* $8F47 PHA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x00F0); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $8F48 AND */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x17), (uint16_t)(g_cpu.C)); /* $8F4B STA */
    recomp_tick(34);
    op_pla16();                                    /* $8F4D PLA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x000F); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $8F4E AND */
    recomp_tick(12);
    op_tay();                                      /* $8F51 TAY */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x4A))); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F52 LDX */
  L_8F54:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x10))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F54 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA0 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8F56 STA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F59 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F5A INX */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $8F5B CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0100); smk_op_adc16(_v); } /* $8F5C ADC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x10), (uint16_t)(g_cpu.C)); /* $8F5F STA */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x12))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F61 LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA0 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8F63 STA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F66 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F67 INX */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $8F68 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0200); smk_op_adc16(_v); } /* $8F69 ADC */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x12), (uint16_t)(g_cpu.C)); /* $8F6C STA */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x16))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $8F6E LDA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, (uint16_t)(0x0EA0 + g_cpu.X), (uint16_t)(g_cpu.C)); /* $8F70 STA */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F73 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F74 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.Y) - 1); g_cpu.Y = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $8F75 DEY */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_8F54;  /* $8F76 BNE */
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x4A), (uint16_t)(g_cpu.X)); /* $8F78 STX */
    recomp_tick(24);
    return;            /* $8F7A RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:BB70
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81BB70, 0x81BB70) {
    goto L_BB70;
  L_BB70:;
    recomp_tick(34);
    { uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x1F26)); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $BB70 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x00FF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB73 AND */
    recomp_tick(18);
    op_xba();                                      /* $BB76 XBA */
    recomp_tick(34);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x1F26)); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB77 EOR */
    recomp_tick(18);
    op_xba();                                      /* $BB7A XBA */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x1F26, (uint16_t)(g_cpu.C)); /* $BB7B STA */
    recomp_tick(18);
    op_xba();                                      /* $BB7E XBA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x00FF); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB7F AND */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)((_x >> 15) & 1); uint16_t _r = (uint16_t)(_x << 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $BB82 ASL */
    recomp_tick(34);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(g_cpu.DB, 0x1F26)); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB83 EOR */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $BB86 LSR */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFF80); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB87 EOR */
    recomp_tick(12);
    if (!g_cpu.flag_C) goto L_BB93;  /* $BB8A BCC */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x8180); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $BB8C EOR */
  L_BB8F:;
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x1F26, (uint16_t)(g_cpu.C)); /* $BB8F STA */
    recomp_tick(24);
    return;            /* $BB92 RTL */
  L_BB93:;
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xAA55); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $BB93 CMP */
    recomp_tick(12);
    if (!g_cpu.flag_Z) goto L_BB8F;  /* $BB96 BNE */
    recomp_tick(34);
    bus_write16(g_cpu.DB, 0x1F26, (uint16_t)(0));  /* $BB98 STZ */
    recomp_tick(24);
    return;            /* $BB9B RTL */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F638
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F638, 0x81F638) {
    goto L_F638;
  L_F638:;
    recomp_tick(12);
    op_txa();                                      /* $F638 TXA */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F639 LDX */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0x0000); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $F63C CMP */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_F6A7;  /* $F63F BEQ */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_F64A;  /* $F641 BPL */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFFFF); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F643 EOR */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F646 INC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0004); g_cpu.X = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F647 LDX */
  L_F64A:;
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x00), (uint16_t)(g_cpu.C)); /* $F64A STA */
    recomp_tick(12);
    op_tya();                                      /* $F64C TYA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_F6B6;  /* $F64D BEQ */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_F657;  /* $F64F BPL */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFFFF); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F651 EOR */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F654 INC */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F655 INX */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.X) + 1); g_cpu.X = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F656 INX */
  L_F657:;
    recomp_tick(28);
    bus_write16(0x00, (uint16_t)(g_cpu.DP + 0x02), (uint16_t)(g_cpu.C)); /* $F657 STA */
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x00))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $F659 CMP */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_F67A;  /* $F65B BCS */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x003F); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F65D LDA */
  L_F660:;
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x00))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $F660 CMP */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_F66A;  /* $F662 BCS */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F664 LSR */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x02)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F666 LSR */
    recomp_tick(12);
    goto L_F660;   /* $F668 BRA */
  L_F66A:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x02))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F66A LDA */
    recomp_tick(18);
    op_xba();                                      /* $F66C XBA */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F66D LSR */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F66E LSR */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F66F CLC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x00))); smk_op_adc16(_v); } /* $F670 ADC */
    recomp_tick(40);
    { uint16_t _t = bus_read16(0x81, (uint16_t)(0xF697 + g_cpu.X)); func_table_call_jsr(((uint32_t)0x81 << 16) | _t); }  /* $F672 JSR */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFF00); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F675 AND */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F678 CLC */
    recomp_tick(24);
    return;            /* $F679 RTL */
  L_F67A:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x003F); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F67A LDA */
  L_F67D:;
    recomp_tick(28);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x02))); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $F67D CMP */
    recomp_tick(12);
    if (g_cpu.flag_C) goto L_F687;  /* $F67F BCS */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x00)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F681 LSR */
    recomp_tick(50);
    { uint8_t _bk = (uint8_t)(0x00); uint16_t _ad = (uint16_t)((uint16_t)(g_cpu.DP + 0x02)); uint16_t _x = bus_read16(_bk, _ad); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); bus_write16(_bk, _ad, _r); g_cpu.flag_C = _c; g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F683 LSR */
    recomp_tick(12);
    goto L_F67D;   /* $F685 BRA */
  L_F687:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x00))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F687 LDA */
    recomp_tick(18);
    op_xba();                                      /* $F689 XBA */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F68A LSR */
    recomp_tick(12);
    { uint16_t _x = (uint16_t)(g_cpu.C); uint8_t _c = (uint8_t)(_x & 1); uint16_t _r = (uint16_t)(_x >> 1); g_cpu.flag_C = _c; g_cpu.C = (uint16_t)((_r) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_r) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_r) == 0); } /* $F68B LSR */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F68C CLC */
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x02))); smk_op_adc16(_v); } /* $F68D ADC */
    recomp_tick(40);
    { uint16_t _t = bus_read16(0x81, (uint16_t)(0xF69F + g_cpu.X)); func_table_call_jsr(((uint32_t)0x81 << 16) | _t); }  /* $F68F JSR */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFF00); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F692 AND */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F695 CLC */
    recomp_tick(24);
    return;            /* $F696 RTL */
  L_F6A7:;
    recomp_tick(12);
    op_tya();                                      /* $F6A7 TYA */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_F6C5;  /* $F6A8 BEQ */
    recomp_tick(12);
    if (!g_cpu.flag_N) goto L_F6B1;  /* $F6AA BPL */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x0000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6AC LDA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6AF CLC */
    recomp_tick(24);
    return;            /* $F6B0 RTL */
  L_F6B1:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x8000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6B1 LDA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6B4 CLC */
    recomp_tick(24);
    return;            /* $F6B5 RTL */
  L_F6B6:;
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.X); uint16_t _v = (uint16_t)(0x0000); uint16_t _t = (uint16_t)(_a - _v); g_cpu.flag_C = (uint8_t)(_a >= _v); g_cpu.flag_Z = (uint8_t)(_a == _v); g_cpu.flag_N = (uint8_t)((_t >> 15) & 1); } /* $F6B6 CPX */
    recomp_tick(12);
    if (g_cpu.flag_Z) goto L_F6C0;  /* $F6B9 BEQ */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0xC000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6BB LDA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6BE CLC */
    recomp_tick(24);
    return;            /* $F6BF RTL */
  L_F6C0:;
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x4000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6C0 LDA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6C3 CLC */
    recomp_tick(24);
    return;            /* $F6C4 RTL */
  L_F6C5:;
    recomp_tick(12);
    g_cpu.flag_C = 1;                              /* $F6C5 SEC */
    recomp_tick(24);
    return;            /* $F6C6 RTL */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6C7
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6C7, 0x81F6C7) {
    goto L_F6C7;
  L_F6C7:;
    recomp_tick(12);
    op_tax();                                      /* $F6C7 TAX */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6C8 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x4000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6C9 LDA */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_adc16(_v); } /* $F6CC ADC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6D0 CLC */
    recomp_tick(24);
    return;            /* $F6D1 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6D2
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6D2, 0x81F6D2) {
    goto L_F6D2;
  L_F6D2:;
    recomp_tick(12);
    op_tax();                                      /* $F6D2 TAX */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x40FF); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6D3 LDA */
    recomp_tick(12);
    g_cpu.flag_C = 1;                              /* $F6D6 SEC */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_sbc16(_v); } /* $F6D7 SBC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6DB CLC */
    recomp_tick(24);
    return;            /* $F6DC RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6DD
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6DD, 0x81F6DD) {
    goto L_F6DD;
  L_F6DD:;
    recomp_tick(12);
    op_tax();                                      /* $F6DD TAX */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0xC0FF); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6DE LDA */
    recomp_tick(12);
    g_cpu.flag_C = 1;                              /* $F6E1 SEC */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_sbc16(_v); } /* $F6E2 SBC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6E6 CLC */
    recomp_tick(24);
    return;            /* $F6E7 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6E8
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6E8, 0x81F6E8) {
    goto L_F6E8;
  L_F6E8:;
    recomp_tick(12);
    op_tax();                                      /* $F6E8 TAX */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6E9 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0xC000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6EA LDA */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_adc16(_v); } /* $F6ED ADC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6F1 CLC */
    recomp_tick(24);
    return;            /* $F6F2 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6F3
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6F3, 0x81F6F3) {
    goto L_F6F3;
  L_F6F3:;
    recomp_tick(12);
    op_tax();                                      /* $F6F3 TAX */
    recomp_tick(12);
    g_cpu.flag_C = 1;                              /* $F6F4 SEC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x80FF); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6F5 LDA */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_sbc16(_v); } /* $F6F8 SBC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F6FC CLC */
    recomp_tick(24);
    return;            /* $F6FD RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F6FE
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F6FE, 0x81F6FE) {
    goto L_F6FE;
  L_F6FE:;
    recomp_tick(12);
    op_tax();                                      /* $F6FE TAX */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F6FF LDA */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F703 CLC */
    recomp_tick(24);
    return;            /* $F704 RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F705
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F705, 0x81F705) {
    goto L_F705;
  L_F705:;
    recomp_tick(12);
    op_tax();                                      /* $F705 TAX */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F706 CLC */
    recomp_tick(18);
    { uint16_t _v = (uint16_t)(0x8000); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F707 LDA */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); smk_op_adc16(_v); } /* $F70A ADC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F70E CLC */
    recomp_tick(24);
    return;            /* $F70F RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $81:F710
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_81F710, 0x81F710) {
    goto L_F710;
  L_F710:;
    recomp_tick(12);
    op_tax();                                      /* $F710 TAX */
    recomp_tick(40);
    { uint16_t _v = (uint16_t)(bus_read16(0x7F, (uint16_t)(0x8FFF + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $F711 LDA */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFF00); _a = (uint16_t)(_a & _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F715 AND */
    recomp_tick(18);
    { uint16_t _a = (uint16_t)(g_cpu.C); uint16_t _v = (uint16_t)(0xFFFF); _a = (uint16_t)(_a ^ _v); g_cpu.C = (uint16_t)((_a) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_a) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_a) == 0); } /* $F718 EOR */
    recomp_tick(12);
    { uint16_t _t = (uint16_t)((g_cpu.C) + 1); g_cpu.C = (uint16_t)((_t) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_t) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_t) == 0); } /* $F71B INC */
    recomp_tick(12);
    g_cpu.flag_C = 0;                              /* $F71C CLC */
    recomp_tick(24);
    return;            /* $F71D RTS */
}

/* Auto-generated by tools/recomp/autogen.py from $85:96DC
 * entry M=0 X=0 (P=$00). Validate with the diff harness. */
RECOMP_PATCH(smk_8596DC, 0x8596DC) {
    goto L_96DC;
  L_96DC:;
    recomp_tick(28);
    { uint16_t _v = (uint16_t)(bus_read16(0x00, (uint16_t)(g_cpu.DP + 0x7E + g_cpu.X))); g_cpu.C = (uint16_t)((_v) & 0xFFFF); g_cpu.flag_N = (uint8_t)(((uint16_t)(_v) >> 15) & 1); g_cpu.flag_Z = (uint8_t)((uint16_t)(_v) == 0); } /* $96DC LDA */
    recomp_tick(30);
    bus_write16(g_cpu.DB, 0x2116, (uint16_t)(g_cpu.C)); /* $96DE STA */
    recomp_tick(24);
    return;            /* $96E1 RTS */
}
